project:
  type: book

book:
  title: "R Models"
  author: "gaoch"
  date: "2023/12/30"
  chapters:
    - index.qmd
    - part: 10.tidymodels-intro.qmd
      chapters: 
        - 11.tidymodels-basic.qmd
        - 12.tidymodels-advanced.qmd
        - 13.tidymodels-extra.qmd 
        - 30.tidymodels-example.qmd
    - part: 20.data-mining.qmd
      chapters: 
        - 21.house-price-pred-lm.qmd
        - 22.insurance-predict.qmd
    - part: 90.conclusion.qmd
  appendices: 
    - 95.references.qmd

bibliography: [r-models-zotero.bib, references.bib]

knitr:
  opts_chunk: 
    echo: true
    collapse: false
    comment: "#>"
    fig.path: "figures/"

format:
  html:
    theme: cosmo
    code-fold: false
    html-math-method: katex
    mermaid:
      theme: forest

  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  docx: default



